"""Create an honest, synthetic technical demo. No sports footage or AI claims."""

import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from fastapi.testclient import TestClient
from server.app import app
from server import db, media, worker


def main():
    with (
        TestClient(app, headers={"X-Storyroom": "local"}) as c,
        tempfile.TemporaryDirectory() as tmp,
    ):
        existing = next(
            (
                p
                for p in c.get("/api/projects").json()
                if p["name"] == "First assembly · technical demo"
            ),
            None,
        )
        if existing:
            print("Demo already exists:", existing["id"])
            return
        p = c.post(
            "/api/projects",
            json={
                "name": "First assembly · technical demo",
                "brief": "A technical demonstration of import, selection, trim, playback, and export. These are generated test patterns, not training footage.",
            },
        ).json()["id"]
        descriptions = [
            "Opening · warm-up test pattern",
            "Progression · movement test pattern",
            "Finish · final test pattern",
        ]
        colors = ["0x53684b", "0x596e8c", "0xac7c58"]
        asset_ids = []
        for i, color in enumerate(colors):
            file = Path(tmp) / f"{i + 1:02}-generated-test-pattern.mp4"
            args = [
                "ffmpeg",
                "-nostdin",
                "-y",
                "-v",
                "error",
                "-f",
                "lavfi",
                "-i",
                f"color=c={color}:s=960x540:r=30:d=4",
                "-f",
                "lavfi",
                "-i",
                f"sine=frequency={330 + i * 110}:duration=4",
                "-vf",
                f"drawbox=x=80+{i * 70}:y=100:w=220:h=220:color=white@0.35:t=fill,drawgrid=w=80:h=80:t=1:c=white@0.06",
                "-c:v",
                "libx264",
                "-pix_fmt",
                "yuv420p",
                "-threads",
                "2",
                "-c:a",
                "aac",
                "-shortest",
                str(file),
            ]
            media.run(args)
            with file.open("rb") as f:
                r = c.post(
                    f"/api/projects/{p}/import",
                    files={"file": (file.name, f, "video/mp4")},
                )
                r.raise_for_status()
                asset_ids.append(r.json()["id"])
        # This script can seed without a running worker. Do not run it alongside the worker.
        while worker.once():
            pass
        for aid in asset_ids:
            c.put(
                f"/api/assets/{aid}/provenance",
                json={
                    "source": "Generated by scripts/demo.py",
                    "author": "Storyroom",
                    "license": "Generated technical fixture; no third-party footage",
                    "cloud_analysis": False,
                    "training": False,
                    "redistribution": True,
                },
            ).raise_for_status()
        board = []
        for i, aid in enumerate(asset_ids):
            board.append(
                {
                    "id": db.uid(),
                    "title": [
                        "Establish the scene",
                        "Show the progression",
                        "Land the ending",
                    ][i],
                    "purpose": [
                        "Introduce the visual setting.",
                        "Explore rhythm and sequence.",
                        "Leave room for a closing moment.",
                    ][i],
                    "selections": [
                        {
                            "id": db.uid(),
                            "asset_id": aid,
                            "moment_id": aid,
                            "start_frame": 15,
                            "end_frame": 105,
                            "note": "Generated fixture — replace with your footage.",
                        }
                    ],
                }
            )
            c.post(
                f"/api/assets/{aid}/moments",
                json={
                    "start_frame": 15,
                    "end_frame": 105,
                    "description": descriptions[i],
                },
            ).raise_for_status()
        c.put(
            f"/api/projects/{p}/board", json={"revision": 0, "sections": board}
        ).raise_for_status()
        for kind in ["render", "export"]:
            c.post(
                f"/api/projects/{p}/jobs/{kind}", json={"query": ""}
            ).raise_for_status()
        while worker.once():
            pass
        print("Generated technical demo:", p)
        for job in c.get(f"/api/projects/{p}").json()["jobs"]:
            print(job["kind"], job["status"], job["message"])


if __name__ == "__main__":
    main()
